#!/usr/bin/python3
RARE = 'rare'
COMMON = 'como'
TOTAL_MINT = 1952
CANISTER_ID = # <str>: Canister ID
PEM_FILE = # <str>: PEM file path
CLIENT_NET = 'https://ic0.app' # this should be a static configuration for the foreseeable future
LOG_FILE = 'airdrop.log' # this log is written to the CWD and is updated in realtime
REPORT_FILE = 'airdrop.report' # this report is written to the CWD upon completion of the airdrop
MAX_TEAM_MINT = 29
TEAM_ADDRESS = # <str> or <None> : Account address for team allocations
ASSET_FOLDER = # <str> : folder path to image files that will be used as the asset.payload
THUMB_FOLDER = # <str> : folder path to image files that will be used as the asset.thumbnail
ASSET_UPDATE_FOLDER = # <str> : folder path to update asset payload [MUST BE NAMED THE SAME AS ORIGINAL]
THUMB_UPDATE_FOLDER = # <str> : folder path to updated asset thumbnails [MUST BE NAMED THE SAME AS ORIGINAL]
ASSET_EXT = '.jpg'
COLLECTION = 'PetBots'
PRINCIPAL = # <str> : principal id of the _minter (canister admin)
ACCOUNTS_FILE = # <str> : file path for account listing. This should be a plain text file containing one address per line
MINT_CORRECTION = 0
